import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { AuthModal } from "../components/authModal";
import { OverlayProvider } from "react-aria";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OverlayProvider>
        <AuthModal>
          <main className="">Your gay</main>
        </AuthModal>
      </OverlayProvider>
    </>
  );
};

export default Home;
