import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { OverlayProvider } from 'react-aria';
import { Posts } from '../../components/posts';
import { onAuthStateChanged, getAuth } from 'firebase/auth';
import { Layout } from '../../components/layouts/dashboard';
import { app } from '../../lib/firebaseConfig';
const Dashboard: NextPage = () => {
  let auth = getAuth(app);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OverlayProvider>
        <Layout>
          <Posts />
        </Layout>
      </OverlayProvider>
    </>
  );
};

export default Dashboard;
